###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-30 08:57:54
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-30 08:58:09
###############################################################

invokables:
	link_data_fieldset_form : Data/Form/LinkDataFieldsetForm
	link_data_create_form : Data/Form/LinkDataCreateForm
	link_data_edit_form : Data/Form/LinkDataEditForm
	link_data_search_form : Data/Form/LinkDataSearchForm